apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-ram
    db: mongo
    env: UAT
  name: deploy-ng-svc01
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30160
  selector:
    app: nginxv1
