---
- hosts:  UAT-servers
  tasks:
    - name: log into docker hub registry
      shell: docker login -u pothakamuri06 -p dckr_pat_e6SaFTjTOJXF43-uCqUsYKW8wjk
    - name: Pull the image from docker hub
      shell: docker pull pothakamuri06/webapp:{{BUILD_NUMBER}}
    - name: Run the container using the Image
      shell: docker run --name=santuspringboot -p 8081:8081 --detach pothakamuri06/webapp:{{BUILD_NUMBER}}
